### ISSUE TITLE
missing gel strip - suggest replacement?

### ISSUE THREAD

**Issue by rsc** [hybridgroup/gopherbot#2]
Hi! I'm trying to build my Gopherbot (Gophercon speaker gift version if it matters) and going over the kit list, and it appears I am missing the [gel strip](https://github.com/hybridgroup/gopherbot/blob/master/assembly/KIT.md#gel-strip). 

Can you suggest where to buy a replacement? Thanks!

**Comment by deadprogram** [comment]
Hello @rsc it should be taped to the inside top of the lid to the box.

The gel itself is the same kind as used for lighting gels in the grey color.

I can also mail you a replacement if you email me your address.

**Comment by rsc** [comment]
Oops, my bad. I tried to consolidate things to make it all fit in my suitcase and I threw away the box without noticing the gel strip taped to it. 

I also did not associate "gel strip" with "lighting gel", although of course that makes sense. I'll just pick up a neutral gel sheet from a lighting shop here. Thanks for your help!
